services:
  - type: web
    name: tehnomarket
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py && sleep 10 && gunicorn wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tehnomarket-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "true"

databases:
  - name: tehnomarket-db
    plan: free
    postgresMajorVersion: 14 